services:
  bot:
    image: kapoowe/llm-vc-discord-bot:latest
    environment:
        #STT Settings:
      - STT_MODEL=whisper-1 #This only matters for openai, and this is currently the only option.
      - STT_ENDPOINT=http://localhost:8001
        #LLM Settings:
      - LLM_ENDPOINT=http://localhost:11434/v1
      - LLM=llama3.2 #Don't include 'Ollama/' for local
      - LLM_api=openai_api_key #not needed for local
        #TTS Settings
      - TTS_TYPE=openai #either "openai" or "speecht5"
      - TTS_MODEL=koboro
      - TTS_VOICE=af_bella
      - OPENAI_TTS_ENDPOINT=http://localhost:8022/v1
      - TTS_ENDPOINT=http://localhost:5000 #This is only for "speecht5" ignore unless you're using it.
        #Discord
      - DISCORD_ID=id #Bot ID
      - DISCORD_TOKEN=token #Bot Token
      - LLM_SYSTEM_PROMPT=
        # If you do not want the bot to be able to answer text messages, set this to false
      - LLM_TEXT=true
      - LLM_TEXT_SYSTEM_PROMPT=
        # PROMPT FREE is used when bot joined in free speech mode
      - LLM_SYSTEM_PROMPT_FREE=
      - BOT_TRIGGERS=bot,chatbot #vocal names for it to respond to. seperated by commas, no spaces.
         # I doubt you need to mess with anything down there
         # Optional settings for RVC (change voice to anyone)
      - RVC=false
      - RVC_ENDPOINT=http://localhost:7865
      - RVC_MODEL=test
      - RVC_F0=2
      - RVC_INDEX_RATE=0.66
      - RVC_PROTECT=0.33

         # Optional settings for Perplexity (internet search)
      - PERPLEXITY=false
      - PERPLEXITY_API=MY_PERPLEXITY_API_KEY
      - PERPLEXITY_MODEL=llama-3-sonar-large-32k-online
      - PERPLEXITY_ENDPOINT=https://api.perplexity.ai

         # Optional settings for Vision (image captioning)
      - VISION=false
      - HUGGING_FACE_API=MY_HUGGING_FACE_API_KEY
      - VISION_ENDPOINT=https://api-inference.huggingface.co/models
      - VISION_MODEL=Salesforce/blip-image-captioning-large
